filter:
    excluded_paths:
        - 'bin/*'
        - 'spec/*'
        - 'features/*'
checks:
    php:
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        encourage_single_quotes: true
        return_doc_comments: true
        avoid_todo_comments: true
        parameters_in_camelcaps: true
        no_long_variable_names:
            maximum: '20'
        parameter_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        uppercase_constants: true
        use_self_instead_of_fqcn: true
        simplify_boolean_return: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        phpunit_assertions: true
        param_doc_comment_if_not_inferrable: true
        overriding_parameter: true
        optional_parameters_at_the_end: true
        newline_at_end_of_file: true
        more_specific_types_in_doc_comments: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        avoid_unnecessary_concatenation: true
        avoid_perl_style_comments: true
        avoid_fixme_comments: true
    javascript: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
