sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.1
    - php: hhvm
      sudo: required
      dist: trusty
      group: edge

before_install:
  - openssl aes-256-cbc -K $encrypted_7bbf7fef4d44_key -iv $encrypted_7bbf7fef4d44_iv -in .travis/phar-private.pem.enc -out .travis/phar-private.pem -d
  - stty cols 120
  - if [[ ! $TRAVIS_PHP_VERSION = hhvm* ]]; then phpenv config-rm xdebug.ini; fi

install:
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpspec run --format=pretty

before_deploy:
  - composer install --no-dev
  - wget -O box.phar https://github.com/box-project/box2/releases/download/2.7.5/box-2.7.5.phar
  - chmod 755 box.phar
  - php -d phar.readonly=0 box.phar build -vv

deploy:
  provider: releases
  api_key:
    secure: QkdCFBxVN9LQrN7McWOqbTkwmKVYd0SblnGVskW5AfSp7MHxMiL8H/tsfjZZF4ouU88cJf2GywtEY8mVr6LDkC6SNaFCO0svOAzhCE16gtZMpWBahZGGnwCQjz6iHrtrQ9EESxQccLmu09zhFw2CJxYD4hYt86rLIde77zGh7abFCm+xnUUaXzI2VwDc57iCZGuKxiRI9qnKokR5sYGyIUPyGpqxVzfAv0q72E989f+HoZX7JIJs+c5ZGrfmnDscnW5CjCW08TIw7cCZoy9+wCdXeUcJIzfFX9v0+GUOkEQVMxGKKnncnOqOyv0texkcQoCUDzLmyubXyv4k4j+pCmzQMhc/aUgtaB1jRpFRGe8+e4sm5/GzySRKRR9+j+MHmFZtUW6UrcWKM2TsC7NgJ16bvQCFcQVu1uY8ecTQmFpBaaUyuLDbD23F4mtTVnRecxybkAglsjrJ943pS3S5FUsHSuzGCAW8NaDSkG1TJZmjkSIZPjTs+fw3x2FKSsgqROnwOyyiH2o3FuSf+RUUJV84C4QqxegaHNYk5dCupEyhsZ4DAur3PVjmZXnqo5bBjv/sa/TwdC+6+/29f20mGtyqT4k8bB31En0JceQSDFfuTKvl8wguy+W0ti5oE6mZZFzLlTXQ0ZjaWoiYmXRk7Bd5qyWKS4P7cjmYOndvU04=
  file:
    - uspec.phar
    - uspec.phar.pubkey
  skip_cleanup: true
  on:
    tags: true
    php: 5.6

notifications:
  email: false
  hipchat:
    rooms:
      secure: b04ros2vb9zz9cLypIEeMTs4uTp2vdvGesIzZIq0xk/aByuptVkgB0/FWS1A9M2XbEdtKkL+E0ZnmbOxxGir6Tt9knl0Cgsrfu/dJFGpmYVjBKM7zLrSK7n0LR5Mx3MW3Knr4YdAaXz2Ke6SepE2ENiDAvUCbjEt1v+DOat+wS9TGu27nsMZbAGpuBKwEgejv6RlOhlETOzm5lfS3/owinR83ktbJZdO9QbYNFGS/51bkkwkU9y4NmywAoCNO2th9hFFgJD4GJHNGg6L/efCnwv5mU71MxmzQZBwxHx8F4M23+aRODxfJ0Wbkow2syhYdd4ptNObgrf7JIbITsZ/IW+M8c0AkCLn0gmFkJNdw1RVDOuGS0lQMWzOg7qQ644VHVQ18m5U2/uhyL5YsAANtvxOvWzVgRaxfaxxGeR0DtxaBLXKerPMMZ41oxwf9iLeUlVM5yt9htPtduWGA1E8Zyz5Ru06x+A9BfKDrPEC3WeoX9h/xziceVzhsk6rHfs9w5NNft8wtj/85jGPmyqJ3XUUBIYvwegv1GVXr04rm4cetFv0fIZbZ/ynHOqvEhh433UaxHrHhE3By0YJ7nRYeZMwtPYhAiCvezl0vI8EF1kJoufplOqX9XNS5Mkz0RM81tFs1PnZOXuuVaXWCwUcZFSsCvYY3WEsqAsxfgtXY8I=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
    notify: true
