sudo: false
language: php

cache:
  directories:
  - $HOME/.composer/cache
  - vendor

matrix:
  fast_finish: true
  include:
  - php: 5.6
    env:
    - EXECUTE_DEPLOYMENT=true
  - php: 7.1
  # Use the newer stack for HHVM as HHVM does not support Precise anymore since a long time and so Precise has an outdated version
  - php: hhvm-3.15
    sudo: required
    dist: trusty
    group: edge
  allow_failures:
  - php: hhvm

before_install:
- stty cols 120
- if [[ ! $TRAVIS_PHP_VERSION = hhvm* ]]; then phpenv config-rm xdebug.ini; fi

install:
- composer install --no-interaction

script:
- ./vendor/bin/phpspec run
